### ISSUE TITLE
APK file for v1.0.6.27 lacks version number

### ISSUE THREAD

**Issue by IzzySoft** [hoihei/Silectric#1]
Looks like the most recent package misses some metadata, so it fails to install/update:

    package: name='net.alaindonesia.silectric' versionCode='' versionName=''

Just to let you know, as you might wish to update and replace it :)

PS: You write you don't have a Google publisher account yet. As your app is open source, I've taken the freedom to make it available via [my F-Droid compatible repo](https://apt.izzysoft.de/fdroid/index/apk/net.alaindonesia.silectric) (only v1.0 now, for the above mentioned reasons) – so if you wish to, you can point your users there. As soon as above issue is fixed, I'll set it up for auto-updates :)

**Comment by hoihei** [comment]
hi @IzzySoft , I update the metadata to fix the version issue.
Current release is https://github.com/hoihei/Silectric/releases/download/v1.0.6.27.1/silectric1.0.6.27.1.apk
Please set up the auto-updates in the app repo now to https://github.com/hoihei/Silectric/releases
thank you very much for your kindness.

**Comment by IzzySoft** [comment]
Done – thanks!

**Comment by IzzySoft** [comment]
@hoihei congrats to your app now being in the official F-Droid repo! To avoid confusion on the users' end, I've "unlisted" it on mine. Should the need arise, be welcome to contact me (e.g. with a note here in this issue) and I can easily re-list it.

**Comment by IzzySoft** [comment]
Ugh, sorry to bring this up again: but for the currently latest release the gradle seems to have no versionCode? It hasn't been updated in F-Droid, probably because of that.
