### ISSUE TITLE
Missing translations error

### ISSUE THREAD

**Issue by est31** [hoihei/Silectric#8]
Hi! F-Droid packager here.

The F-Droid build of the 1.2 release of your app [fails](https://f-droid.org/wiki/index.php?title=net.alaindonesia.silectric/lastbuild_1220161204&oldid=121797) because of a linter error about missing translations.

Can you either disable the linter in the build.gradle or fix the translations? Thank you!

**Comment by hoihei** [comment]
Hi @est31,
We have fixed the translation error and we have update the release version app into 1.2.01 
Thank you for your help.

**Comment by est31** [comment]
Thanks for the help!
